title: "My Site"
tagline: ""
description: ""
github_username: "Sussy"
baseurl: ""
url: "https://vagos.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

collections:

  entries: 
    output: true

  drafts:
    output: false

header_pages:
  - pages/index.md
  - pages/things.md
  - pages/about.md
  - pages/posts.md

# set the size of the text to 'large' or 'small', default is small
font-size: small

feed:
  collections:
    - entries
